apiVersion: v1
kind: Service
metadata:
  name: student-backend-service
spec:
  type: LoadBalancer
  selector:
    app: student-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
